### ISSUE TITLE
add status badge?

### ISSUE THREAD

**Issue by maelle** [jumpingrivers/HIBPwned#12]
@stephlocke do you want to start using status badges in your repos?

If so, do you prefer [tidyverse badges](https://www.tidyverse.org/lifecycle/) or [repostatus.org badges](http://www.repostatus.org/)? At rOpenSci it was decided to start using the latter. I think repostatus.org badges are more general, and I have helpers for them [here](https://github.com/ropenscilabs/rodev) similar to `usethis` helpers for lifecycle badges.

**Comment by stephlocke** [comment]
go forth and badge! I have no badge preferences tho I did do a PR for https://github.com/RMHogervorst/badgecreatr in the past

**Comment by maelle** [comment]
oooh I had forgotten about this pkg!
