### ISSUE TITLE
write 2 blog posts when new version on CRAN

### ISSUE THREAD

**Issue by maelle** [jumpingrivers/HIBPwned#21]

**Comment by stephlocke** [comment]
and update superbuild so the latest version of the docs deploy

**Comment by maelle** [comment]
😱 should I rename this issue "Enter git submodule hell and try to exit successfully"? 😂

**Comment by maelle** [comment]
use case started [here](https://github.com/lockedata/metacranpwned)

**Comment by maelle** [comment]
at the end give advice for pwned "change password in other locations is you reuse password, use a password manager, set up two factor authentication" thx @stephlocke

**Comment by maelle** [comment]
# Blog post 1: Here's HIBPwned and why one would use it (w/metacran analysis)

See [this repo](https://github.com/lockedata/metacranpwned)

# Blog post 2: Here's why HIBPwned is a great API pkg to emulate

* `crul` (no real good reason in itself, except the name [crolute](http://www.masalmon.eu/2017/06/30/crolute/))

* `webmockr` (which only works with `crul`currently -- otherwise one could use [`httptest`](https://github.com/nealrichardson/httptest)))

* `memoise`, quite nice for the API. For paid services, it'd be useful too. `opencage` implements memoise. Unless the data changes within an R session, it's a fine thing to have.

* `ratelimitr`. With this, the developer doesn't need to think a lot to implement rate limiting, and the user doesn't need to deal with 422 errors.

* the use of an agent. maybe I could find a link telling why it's better.

* Future work would be to improve the `webmockr` test cf in particular [this question of mine `](https://github.com/ropensci/webmockr/issues/31)
