### ISSUE TITLE
gitleaks

### ISSUE THREAD

**Issue by maelle** [jumpingrivers/HIBPwned#3]
h/t @sckott

https://github.com/zricethezav/gitleaks

Maybe it could be a function of `HIBPwned` 🤔 search someone's repo (as argument) or all repos (by using GitHub API to retrieve the repos of the user)

**Comment by maelle** [comment]
https://romain.rbind.io/blog/2017/06/09/go-packages-in-r-packages/ (but I guess adapting the go code into R code might be easier)

**Comment by stephlocke** [comment]
I'd like to keep this purely a wrapper of the HaveIBeenPwned API

**Comment by maelle** [comment]
👍
