### ISSUE TITLE
ERROR on OSX oldrel on CRAN

### ISSUE THREAD

**Issue by maelle** [jumpingrivers/HIBPwned#4]
* Add a build matrix to Travis config file to reproduce this error.

@stephlocke btw could you give me some rights to this repo please? 🙏  I'll do a PR anyway but I'd like this issue to be officially assigned to me 😀

**Comment by maelle** [comment]
I currently haven't been able to reproduce the error 😱 

Meanwhile, I got other errors, that I assume are due to the website sometimes not returning a result, so I added trying&waiting.

**Comment by stephlocke** [comment]
Invited.

It not returning values must mean there's some ratelimitr calls missing somewhere - or it's because it don't have a global timer which maybe it should

**Comment by maelle** [comment]
I made it disappear with wishful thinking 😜
