### ISSUE TITLE
Output of account_breaches

### ISSUE THREAD

**Issue by maelle** [jumpingrivers/HIBPwned#5]
The function currently returns a list of data.frames. Should they be a single data.frame with an email address variable instead?

**Comment by stephlocke** [comment]
There's info on each breach split by name iirc - if you think it'd be easier to consume as a single table with the breach info and which email was breached (which you're probably right about!) then go for it. 
Will probably need to make things super clear that this is a breaking change - and/or have a flag for using the old behaviour.
