### ISSUE TITLE
Add tests for the waiting and trying

### ISSUE THREAD

**Issue by maelle** [jumpingrivers/HIBPwned#9]
For that, use `webmockr`.

If I do that soon, I'll also need to replace `httr` with `crul` https://github.com/ropensci/webmockr

Or I could use the testing package which works with `httr` but I'm less enclined to do so. 🤔

**Comment by stephlocke** [comment]
Swapping out httr is a fairly large task - aside of making it a bit easier to test, are there other benefits?

**Comment by maelle** [comment]
No, well `crul` e.g. supports asynchronous requests but I think `httr` does now?

In any case, this wouldn't be something for the very next release I think.

**Comment by stephlocke** [comment]
okie dokie :)

**Comment by maelle** [comment]
First experiments with my I16 branch

```r
library(crul)
library(testthat)

# make a stub
webmockr::enable()
stub <- webmockr::stub_request("get", "https://haveibeenpwned.com/api/breaches")
webmockr::to_return(stub, status = 404)
webmockr::stub_registry()
HIBPwned::breached_sites()
webmockr::disable()

head(HIBPwned::breached_sites())

```

**Comment by maelle** [comment]
will `skip_on_cran()` because these tests take a little while
